#!/bin/bash                 
# xbujzad00 David Bujzaš 
# 26.2.2024

export POSIXLY_CORRECT=yes
export LC_ALL=C

after=""
before=""
currency=""
com=""
user=""

helpMessage() {
    echo "Usage: $0 [-h|--help] [FILTER] [COMMAND] USER LOG [LOG2 [...]]"
    echo "Help:"
    echo "  -h, --help      Display this help message"
    echo "Filters:"
    echo "  -a              Filter after the input date"
    echo "  -b              Filter before the input date"
    echo "  -c              Filter by currency"
    echo "Commands:"
    echo "  list            List of records for input user"
    echo "  list-currency   Sorted list of currencies in the file"
    echo "  status          Statement of actual account balances grouped and sorted by currency"
    echo "  profit          The customer's account statement with the fictitious return included."
}

# checks if the input date is valid
checkDate() {
    if date -d "$1" > /dev/null 2>&1; then
        return 0
    else
        echo "Invalid date format." >&2
        exit 1
    fi
}

checkFile() {
    # checks if all the columns in file are valid using regex and filters the list with arguments input from .log or .gz file by the user using awk
    awk -F ';' -v currency="$currency" -v before="$before" -v after="$after" -v user="$user" -v userFormat="$userFormat" -v curFormat="$curFormat" -v numFormat="$numFormat" '
        function isValidUser(user) {
            return (user ~ userFormat);
        }
        function isValidDate(date) {
            dateCmd = "date -d \"" date "\" >/dev/null 2>&1"
            return (system(dateCmd) == 0);
        }
        function isValidCurrency(cur) {
            return (cur ~ curFormat);
        }
        function isValidNumber(num) {
            return (num ~ numFormat);
        }
        ( !isValidUser($1) || !isValidDate($2) || !isValidCurrency($3) || !isValidNumber($4) ) {
            print "Invalid format in file: " $0 > "/dev/stderr";
            exit 1;
        }
        ( ($3 == currency || currency == "") && ($1 == user) && ($2 < before || before == "") && ($2 > after || after == "") )'
}


# filters the list
filter() {
    # regex user format
    userFormat='[[:print:]]+$'
    # regex currency format
    curFormat='^[A-Za-z]{3}$'
    # regex number format
    numFormat='[-]?[0-9]+.[0-9]+$'
    
    # iterates through files in the file array
    for file in "${files[@]}"; do
        # checks if the file doesn't have .gzip file extension
        if [[ $(file -b "$file") != *"gzip compressed data"* ]]; then
            # if fields are empty it exits with 1 and triggers the error message
            if awk -F ';' '($1 == "" || $2 == "" || $3 == "" || $4 == "") { exit 1 }' "$file"; then
                cat < "$file" | checkFile
            else
                echo "Fields are empty in $file." >&2
                exit 1
            fi
        else
            # if fields are empty it exits with 1 and triggers the error message
            if gzip -dc "$file" | awk -F ';' '($1 == "" || $2 == "" || $3 == "" || $4 == "") { exit 1 }'; then
                gzip -dc "$file" | checkFile
            else
                echo "Fields are empty in $file." >&2
                exit 1
            fi
        fi
    done
}

# lists the users currency
listCurrency() {
    filter | awk -F ';' '{print $3}' | sort | uniq
}

# sums up all the currencies into one
status() {
    filter | awk -F ';' '{sum[$3] += $4} 
    END {
        for(currency in sum) {
            printf "%s : %.4f\n", currency, sum[currency]
        }
    }' | sort
}

# sums up all the currencies into one, if they are greater than 0 adds up profit
# if XTF_PROFIT is not set, sets it to default value (20)
profit() {
    filter | awk -F ';' -v profit="$XTF_PROFIT" '{sum[$3] += $4} 
    END {
        for(currency in sum) {
            if(sum[currency] > 0) {
                if(profit == "") {
                    profit = 20
                }
                sum[currency] *= 1 + profit/100
            }
            printf "%s : %.4f\n", currency, sum[currency]
        }
    }' | sort
}

# if there are no arguments output error
if [ $# -eq 0 ]; then
    echo "Enter at least one argument to run the script." >&2
    exit 1
fi

# if the first index is -h or --help output the help message
case "$1" in 
    "-h" | "--help")
        helpMessage
        exit 0
        ;;
esac

# parsing filter arguments
while getopts "a:b:c:" opt; do
    case $opt in
        a)
            if [ -n "$after" ]; then
                echo "The filter -a cannot be entered more than once." >&2
                exit 1
            fi

            if  checkDate "$OPTARG"; then
                after=$OPTARG
            fi
            ;;
        b)
            if [ -n "$before" ]; then
                echo "The filter -b cannot be entered more than once." >&2
                exit 1
            fi

            if checkDate "$OPTARG"; then
                before=$OPTARG
            fi
            ;;
        c)
            currency="$OPTARG"
            if [[ ! "$currency" =~ ^[A-Za-z]{3}$ ]]; then
                echo "The currency is in the wrong format." >&2
                exit 1
            fi
            ;;
        *)
            echo "You have entered an invalid filter. Try again." >&2
            exit 1 
            ;;
    esac
done

# shifts filters
shift $((OPTIND-1))

# sets command variable to the user input command
case "$1" in
    "list" | "list-currency" | "status" | "profit")
        com="$1"
        shift
        ;;
    *)
        com="list"
        ;;
esac

# if the string on index 1 is not empty or is not a file sets user to string on index 1
if [ -n "$1" ] && [ ! -f "$1" ]; then
    user="$1"
    shift
else
    echo "Invalid trader." >&2
    exit 1
fi

files=("$@")

# iterates through files array and checks if the file is valid
for file in "${files[@]}"; do
    if [ ! -f "$file" ]; then
        echo "$file is not a valid file." >&2
        exit 1
    fi
done

# if there are no files input output error message
if [ ${#files[@]} -eq 0 ]; then
    echo "No files were input." >&2
    exit 1
fi

# switches commands based on user input
case "$com" in
    "list")
        filter
        ;;
    "list-currency")
        listCurrency
        ;;
    "status")
        status
        ;;
    "profit")
        profit
        ;;
    *)
        echo "You have entered an invalid command. Try again." >&2
        exit 1
        ;;
esac
